server:
  port: 9010

spring:
  application:
    name: qy-cloud-bookmark-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      ## 路由
      routes:
        - id: auth_route
          uri: lb://qy-cloud-bookmark-auth
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/login, /oauth/token
        - id: system_route
          uri: lb://qy-cloud-bookmark-service-system
          predicates:
            - Path=/api/announcement/**
          filters:
            - name: Hystrix
              args:
                name: fallback
                fallbackUri: 'forward:/fallback'

        - id: user_route
          uri: lb://qy-cloud-bookmark-service-user
          predicates:
            - Path=/api/user/**
          filters:
            - name: Hystrix
              args:
                name: fallback
                fallbackUri: 'forward:/fallback'

    loadbalancer:
      retry:
        enabled: true