server:
  port: 9010

spring:
  application:
    name: qy-cloud-bookmark-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      ## 路由
      routes:
        - id: system_route
          uri: lb://qy-cloud-bookmark-service-system
          predicates:
            - Path=/api/announcement/**



    loadbalancer:
      retry:
        enabled: true