server:
  port: 9090
spring:
  application:
    name: qy-cloud-bookmark-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: properties

